import { type ProjectData } from "@/components/ProjectDetailsModal";

export const allProjectsData: ProjectData[] = [
  {
    id: "przypominacz",
    title: "Przypominacz Tasks & Planner",
    category: "saas",
    categoryLabel: "SaaS / Produktywność",
    description:
      "Aplikacja do organizacji zadań, celów i planowania dnia z podziałem na widok TODAY, priorytetyzacją i powiadomieniami.",
    fullDescription:
      "Kompleksowy system zarządzania czasem i zadaniami. Oferuje inteligentne grupowanie zadań na dany dzień (zakładka TODAY), powiadomienia przeglądarkowe, wsparcie dla trybu offline oraz przejrzysty interfejs sprzyjający skupieniu i eliminacji prokrastynacji.",
    tags: ["React 19", "TypeScript", "Tailwind CSS", "IndexedDB", "Zustand"],
    accent: "from-blue-500/20 to-indigo-500/10",
    accentBorder: "hover:border-blue-500/40",
    accentGlow: "0 0 35px -5px rgba(59,130,246,0.25)",
    image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=500&fit=crop",
    demo: "https://przypominacz.vercel.app/?tab=TODAY",
    featured: true,
    stats: { year: "2025", type: "SaaS" },
    metrics: [
      { label: "Czas synchronizacji", value: "< 15ms" },
      { label: "Wzrost produktywności", value: "+85%" },
      { label: "Offline-First", value: "100% PWA" },
    ],
    keyFeatures: [
      "Dedykowana zakładka TODAY z priorytetyzacją zadań na dany dzień",
      "Szybkie dodawanie zadań ze skrótami klawiszowymi",
      "Przechowywanie danych w pamięci lokalnej z opcją kopii chmurowej",
      "Tagowanie, kategorie oraz szacowanie czasu wykonania",
    ],
    architecture: [
      "Architektura React 19 z komponentami Server/Client",
      "Stan zarządzany za pomocą Zustand z persistencją",
      "Stylowanie Zero-Runtime z Tailwind CSS",
    ],
  },
  {
    id: "budowlancy",
    title: "Budowlańcy Portal Usługowy",
    category: "saas",
    categoryLabel: "Marketplace & Usługi",
    description:
      "Platforma łącząca inwestorów z wykonawcami budowlanymi i ekipami remontowymi z systemem weryfikacji i portfolio.",
    fullDescription:
      "Specjalistyczny portal marketplace dla branży budowlano-remontowej. Umożliwia dodawanie zleceń, przeglądanie zweryfikowanych ekip, kalkulację kosztów materiałów oraz bezpośredni kontakt przez zintegrowany komunikator.",
    tags: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "Tailwind"],
    accent: "from-amber-500/20 to-yellow-500/10",
    accentBorder: "hover:border-amber-500/40",
    accentGlow: "0 0 35px -5px rgba(245,158,11,0.25)",
    image: "https://images.unsplash.com/photo-1541888946425-d0fbb180c5f5?w=800&h=500&fit=crop",
    demo: "https://budowlancy.vercel.app/",
    featured: true,
    stats: { year: "2025", type: "Marketplace" },
    metrics: [
      { label: "Baza wykonawców", value: "300+ firm" },
      { label: "Czas odpowiedzi", value: "< 2 godz." },
      { label: "Weryfikacja", value: "100% Certyfikat" },
    ],
    keyFeatures: [
      "Katalog certyfikowanych ekip z opiniami i galeriami realizacji",
      "Generator zapytań ofertowych dla inwestorów indywidualnych",
      "Filtrowanie po województwach, miastach i specjalizacjach",
    ],
    architecture: [
      "Server-Side Rendering (SSR) z Next.js dla maksymalnego SEO",
      "Baza danych PostgreSQL z optymalizacją zapytań Prisma ORM",
    ],
  },
  {
    id: "dymek",
    title: "Dymek Vape & Smoke Lounge",
    category: "ecommerce",
    categoryLabel: "E-commerce & Lounge",
    description:
      "Nowoczesny sklep internetowy i platforma rezerwacji strefy lounge z katalogiem liquidów, akcesoriów i wydarzeń.",
    fullDescription:
      "Kompleksowy serwis łączący sklep internetowy produktów vape i akcesoriów z modułem rezerwacji miejsc w strefie chillout lounge. Ciemny motyw z neonowymi akcentami tworzy unikalny klimat.",
    tags: ["React", "TypeScript", "Stripe API", "Motion", "Tailwind"],
    accent: "from-pink-500/20 to-rose-500/10",
    accentBorder: "hover:border-pink-500/40",
    accentGlow: "0 0 35px -5px rgba(236,72,153,0.25)",
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=800&h=500&fit=crop",
    demo: "https://dymek.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "E-commerce" },
    metrics: [
      { label: "Konwersja sklepu", value: "4.8%" },
      { label: "Rezerwacje online", value: "+180%" },
      { label: "Google Score", value: "99/100" },
    ],
    keyFeatures: [
      "Wielopoziomowy filtr mocy, smaków i pojemności produktów",
      "Wirtualna rezerwacja stolików w strefie lounge",
      "Integracja płatności online i weryfikacja wieku 18+",
    ],
    architecture: [
      "Architektura SPA w React z płynnymi przejściami Motion",
      "Bezpieczny checkout ze Stripe i webhookami statusu",
    ],
  },
  {
    id: "pdf-seven-orcin",
    title: "PDF Tools Studio Pro",
    category: "saas",
    categoryLabel: "SaaS / Narzędzia",
    description:
      "Przeglądarkowy konwerter, kompresor i edytor plików PDF przetwarzający dokumenty w 100% lokalnie przez WebAssembly.",
    fullDescription:
      "Zaawansowany zestaw narzędzi do pracy z plikami PDF wprost w przeglądarce. Zapewnia 100% prywatności — pliki nie są wysyłane na serwer, a cała konwersja, łączenie i dzielenie odbywa się w pamięci klienta za pomocą WebAssembly.",
    tags: ["WebAssembly", "PDF-lib", "TypeScript", "React", "Tailwind"],
    accent: "from-red-500/20 to-orange-500/10",
    accentBorder: "hover:border-red-500/40",
    accentGlow: "0 0 35px -5px rgba(239,68,68,0.25)",
    image: "https://images.unsplash.com/photo-1568667256549-094345857637?w=800&h=500&fit=crop",
    demo: "https://pdf-seven-orcin.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Narzędzie" },
    metrics: [
      { label: "Prywatność", value: "100% Client-Side" },
      { label: "Czas łączenia PDF", value: "< 0.3s" },
      { label: "Limit rozmiaru", value: "Bez limitu" },
    ],
    keyFeatures: [
      "Łączenie, rozdzielanie, obracanie i kompresja dokumentów PDF",
      "Konwersja obrazów JPG/PNG do formatu PDF",
      "Zerowy upload na serwer gwarantujący pełne bezpieczeństwo danych",
    ],
    architecture: [
      "Przetwarzanie dokumentów silnikiem PDF-lib i Web Workers",
      "Asynchroniczne kolejkowanie operacji bez blokowania wątku UI",
    ],
  },
  {
    id: "thc-beige",
    title: "Green Leaf CBD & Dispensary",
    category: "ecommerce",
    categoryLabel: "E-commerce & Zdrowie",
    description:
      "Sklep konopny z certyfikowanymi olejkami CBD, suszem i kosmetykami z filtrowaniem stężeń kannabinoidów.",
    fullDescription:
      "Elegancka platforma e-commerce dedykowana produktom konopnym i CBD. Zawiera bazę wiedzy o terpenach, certyfikaty laboratoryjne produktów oraz szybki koszyk z natychmiastową kalkulacją wysyłki.",
    tags: ["React", "TypeScript", "Shopify API", "Tailwind CSS", "Zustand"],
    accent: "from-emerald-500/20 to-green-500/10",
    accentBorder: "hover:border-emerald-500/40",
    accentGlow: "0 0 35px -5px rgba(16,185,129,0.25)",
    image: "https://images.unsplash.com/photo-1536939459926-301728717817?w=800&h=500&fit=crop",
    demo: "https://thc-beige.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "E-commerce" },
    metrics: [
      { label: "Certyfikaty CoA", value: "100% Partii" },
      { label: "Szybkość koszyka", value: "0.2s" },
      { label: "Średnia ocena", value: "4.95 ★" },
    ],
    keyFeatures: [
      "Filtrowanie stężeń CBD/CBG i profili terpenowych",
      "Karty wyników badań laboratoryjnych przy każdym produkcie",
      "One-page checkout z obsługą płatności natychmiastowych",
    ],
    architecture: [
      "Headless E-commerce zintegrowany z API Shopify",
      "Optymalizacja grafik produktów z formatem WebP",
    ],
  },
  {
    id: "wytrzezwialka",
    title: "Wytrzeźwiałka BAC Telemetry",
    category: "web",
    categoryLabel: "Aplikacja Webowa",
    description:
      "Precyzyjny kalkulator stężenia alkoholu we krwi (BAC) i czasu do pełnego wytrzeźwienia oparty na zmodyfikowanym wzorze Widmarka.",
    fullDescription:
      "Narzędzie analityczne dla kierowców i osób dbających o bezpieczeństwo. Oblicza krzywą wchłaniania i eliminacji alkoholu z organizmu z uwzględnieniem płci, masy ciała, czasu spożywania oraz posiłków.",
    tags: ["React", "TypeScript", "Recharts", "Math Engine", "Tailwind"],
    accent: "from-cyan-500/20 to-blue-500/10",
    accentBorder: "hover:border-cyan-500/40",
    accentGlow: "0 0 35px -5px rgba(6,182,212,0.25)",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=500&fit=crop",
    demo: "https://wytrzezwialka.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Kalkulator" },
    metrics: [
      { label: "Algorytm", value: "Rozszerzony Widmark" },
      { label: "Wizualizacja", value: "Wykres 24h" },
      { label: "Dostępność", value: "Mobilna PWA" },
    ],
    keyFeatures: [
      "Dynamiczny wykres krzywej stężenia promili w czasie",
      "Kalkulacja godziny osiągnięcia 0.00‰ oraz limitu 0.20‰",
      "Katalog popularnych trunków i możliwość dodawania własnych",
    ],
    architecture: [
      "Silnik matematyczny w TypeScript z pełnym pokryciem testami",
      "Renderowanie wykresów w czasie rzeczywistym z Recharts",
    ],
  },
  {
    id: "wycenka",
    title: "Wycenka Pro Estimator",
    category: "saas",
    categoryLabel: "SaaS / Kalkulator",
    description:
      "Interaktywny kalkulator kosztorysów remontowych z natychmiastowym przeliczaniem cen robocizny, materiałów i eksportem do PDF.",
    fullDescription:
      "Aplikacja ułatwiająca klientom i fachowcom przygotowanie rzetelnej wyceny prac wykończeniowych. Pozwala na zdefiniowanie metrażu, wybór standardu (ekonomiczny, standard, premium) i generowanie gotowego kosztorysu ofertowego.",
    tags: ["React", "TypeScript", "jsPDF", "Tailwind", "Zustand"],
    accent: "from-purple-500/20 to-violet-500/10",
    accentBorder: "hover:border-purple-500/40",
    accentGlow: "0 0 35px -5px rgba(139,92,246,0.25)",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&h=500&fit=crop",
    demo: "https://wycenka.vercel.app/",
    featured: false,
    stats: { year: "2025", type: "SaaS" },
    metrics: [
      { label: "Oszczędność czasu", value: "-90%" },
      { label: "Generowanie PDF", value: "< 0.5s" },
      { label: "Pozycje w bazie", value: "150+ prac" },
    ],
    keyFeatures: [
      "Intuicyjny podział na etapy: hydraulika, elektryka, płytki, malowanie",
      "Eksport profesjonalnie sformatowanego kosztorysu PDF z logo firmy",
      "Zapisywanie i edycja wcześniejszych wycen w przeglądarce",
    ],
    architecture: [
      "Reaktywny model kalkulacji z Zustand",
      "Generowanie wektorowych dokumentów PDF po stronie klienta",
    ],
  },
  {
    id: "koty2",
    title: "Kociarnia & Adopcja Zwierząt",
    category: "web",
    categoryLabel: "Społeczność & Adopcja",
    description:
      "Serwis adopcyjny dla kotów ze schronisk z ankietą dopasowania, historią medyczną i interaktywną galerią podopiecznych.",
    fullDescription:
      "Projekt społeczny wspierający adopcję bezdomnych kotów. Użytkownicy mogą przeglądać profile zwierząt, sprawdzać ich charakter, wymagania behawioralne oraz złożyć wniosek adopcyjny online.",
    tags: ["React", "TypeScript", "Tailwind CSS", "Motion", "REST API"],
    accent: "from-rose-500/20 to-pink-500/10",
    accentBorder: "hover:border-rose-500/40",
    accentGlow: "0 0 35px -5px rgba(244,63,94,0.25)",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=500&fit=crop",
    demo: "https://koty2.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Adopcja" },
    metrics: [
      { label: "Udana adopcja", value: "120+ kotów" },
      { label: "Czas ładowania", value: "0.38s" },
      { label: "Dostępność WCAG", value: "100% AA" },
    ],
    keyFeatures: [
      "Karty zwierząt z filtrami wieku, płci, tolerancji na inne zwierzęta",
      "Ankieta przedadopcyjna z walidacją danych",
      "Wirtualne wsparcie i zbiórki na karmę/leczenie",
    ],
    architecture: [
      "Komponentowa struktura React zoptymalizowana pod kątem Core Web Vitals",
      "Lekkie animacje Motion z minimalnym narzutem CPU",
    ],
  },
  {
    id: "kroki2",
    title: "Kroki Fitness & Challenge",
    category: "web",
    categoryLabel: "Zdrowie & Grywalizacja",
    description:
      "Aplikacja do monitorowania kroków, wyzwań fitness i spalonych kalorii z tabelami wyników i odznakami motywacyjnymi.",
    fullDescription:
      "Grywalizacyjna platforma wspierająca codzienne nawyki ruchowe. Zawiera statystyki tygodniowe i miesięczne, system poziomów oraz wirtualne trasy do pokonania (np. spacer przez polskie parki narodowe).",
    tags: ["React", "PWA", "TypeScript", "IndexedDB", "Tailwind"],
    accent: "from-teal-500/20 to-emerald-500/10",
    accentBorder: "hover:border-teal-500/40",
    accentGlow: "0 0 35px -5px rgba(20,184,166,0.25)",
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=500&fit=crop",
    demo: "https://kroki2.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Fitness PWA" },
    metrics: [
      { label: "Dzienny cel", value: "10 000 kroków" },
      { label: "Bateria", value: "Zoptymalizowana" },
      { label: "Wsparcie PWA", value: "iOS / Android" },
    ],
    keyFeatures: [
      "Automatyczne przeliczanie kroków na kalorie i kilometry",
      "Odznaki za regularność i osiąganie rekordów",
      "Tryb offline z pełną synchronizacją po powrocie do sieci",
    ],
    architecture: [
      "Progresywna aplikacja webowa (PWA) z Service Workerami",
      "Lokalna baza danych IndexedDB dla maksymalnej wydajności",
    ],
  },
  {
    id: "piwo-mierz",
    title: "Piwomierz Craft Tracker",
    category: "web",
    categoryLabel: "Social & Dziennik",
    description:
      "Katalog i dziennik degustacji piw rzemieślniczych z ocenami w skali sensorycznej, statystykami stylów i mapą lokali.",
    fullDescription:
      "Aplikacja stworzona dla entuzjastów piw rzemieślniczych (kraftowych). Umożliwia rejestrowanie wypitych pozycji, ocenianie barwy, aromatu, smaku i goryczki (IBU) oraz generowanie wykresów preferencji smakowych.",
    tags: ["React", "TypeScript", "Tailwind", "Zustand", "Lucide Icons"],
    accent: "from-yellow-500/20 to-amber-500/10",
    accentBorder: "hover:border-yellow-500/40",
    accentGlow: "0 0 35px -5px rgba(234,179,8,0.25)",
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&h=500&fit=crop",
    demo: "https://piwo-mierz-main.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Dziennik" },
    metrics: [
      { label: "Style piwa", value: "80+ kategorii" },
      { label: "Ocena sensoryczna", value: "Skala 1-5★" },
      { label: "Eksport danych", value: "JSON / CSV" },
    ],
    keyFeatures: [
      "Radar sensoryczny profilu smakowego (słodowe, chmielowe, kwaśne)",
      "Szybkie dodawanie zdjęć etykiet i notatek degustacyjnych",
      "Statystyki najczęściej wybieranych stylów (IPA, Stout, Sour)",
    ],
    architecture: [
      "Zarządzanie stanem w pamięci lokalnej z Zustand",
      "W pełni responsywny interfejs zoptymalizowany pod kątem ekranów dotykowych",
    ],
  },
  {
    id: "cwaniak",
    title: "Cwaniak Deal Hunter",
    category: "saas",
    categoryLabel: "E-commerce & Promocje",
    description:
      "Społecznościowy agregator okazji, promocji i błędów cenowych z systemem głosowania temperaturą i powiadomieniami.",
    fullDescription:
      "Platforma do wyszukiwania najlepszych zniżek i promocji w polskich sklepach internetowych. Społeczność ocenia oferty, komentuje ich opłacalność oraz oznacza wygasłe kody rabatowe.",
    tags: ["React", "Node.js", "TypeScript", "Tailwind", "WebSockets"],
    accent: "from-orange-500/20 to-red-500/10",
    accentBorder: "hover:border-orange-500/40",
    accentGlow: "0 0 35px -5px rgba(249,115,22,0.25)",
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop",
    demo: "https://cwaniak-nine.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Społeczność" },
    metrics: [
      { label: "Okazje tygodniowo", value: "500+" },
      { label: "Średnia oszczędność", value: "35%" },
      { label: "Aktualizacja", value: "Co 60 sekund" },
    ],
    keyFeatures: [
      "System głosowania na okazje (temperatura okazji)",
      "Filtrowanie według kategorii: elektronika, moda, dom, gry",
      "Weryfikacja historii cen w innych sklepach",
    ],
    architecture: [
      "Dwukierunkowa komunikacja WebSocket dla aktualizacji głosów na żywo",
      "Optymalizacja zapytań z React Query i cache'owaniem odpowiedzi",
    ],
  },
  {
    id: "pizzeria-kaczy1",
    title: "Pizzeria Kaczy Express",
    category: "ecommerce",
    categoryLabel: "E-commerce / Gastro",
    description:
      "System zamówień online z interaktywnym kreatorem pizzy pół na pół, wyborem ciasta, sosów i trackingiem dostawy.",
    fullDescription:
      "Dedykowana aplikacja gastronomiczna dla pizzerii łącząca apetyczny design z intuicyjnym procesem zamówienia. Obsługuje kreator pizzy z własnymi składnikami, kody rabatowe oraz podgląd statusu wypieku.",
    tags: ["React", "TypeScript", "Tailwind CSS", "State Machine", "Audio"],
    accent: "from-red-500/20 to-amber-500/10",
    accentBorder: "hover:border-red-500/40",
    accentGlow: "0 0 35px -5px rgba(220,38,38,0.25)",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=500&fit=crop",
    demo: "https://pizzeria-kaczy1.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "E-commerce" },
    metrics: [
      { label: "Czas złożenia zamówienia", value: "< 50s" },
      { label: "Wzrost sprzedaży online", value: "+160%" },
      { label: "Zadowolenie gości", value: "5.0 ★" },
    ],
    keyFeatures: [
      "Kreator pizzy z dynamicznym podglądem składników",
      "Kalkulator kosztu dostawy na podstawie strefy i kodu pocztowego",
      "Powiadomienia dźwiękowe o statusie zamówienia",
    ],
    architecture: [
      "Modelowanie koszyka maszyną stanów dla wyeliminowania błędów",
      "Lekkie efekty dźwiękowe Web Audio API podnoszące wrażenia UX",
    ],
  },
  {
    id: "tramwaj",
    title: "Tramwaj Live Szczecin GPS",
    category: "web",
    categoryLabel: "Aplikacja Web & GPS",
    description:
      "Monitorowanie pozycji tramwajów i autobusów miejskich w Szczecinie w czasie rzeczywistym z estymacją czasu przyjazdu.",
    fullDescription:
      "Aplikacja transportowa dla mieszkańców Szczecina. Prezentuje rzeczywiste pozycje pojazdów ZDiTM na interaktywnej mapie z uwzględnieniem opóźnień, zmian tras i aktualnych rozkładów jazdy.",
    tags: ["React", "Leaflet Maps", "Realtime GTFS", "TypeScript", "Tailwind"],
    accent: "from-sky-500/20 to-blue-500/10",
    accentBorder: "hover:border-sky-500/40",
    accentGlow: "0 0 35px -5px rgba(2,132,199,0.25)",
    image: "https://images.unsplash.com/photo-1557223562-6c77ef16210f?w=800&h=500&fit=crop",
    demo: "https://tramwaj.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Transport GPS" },
    metrics: [
      { label: "Odświeżanie GPS", value: "Co 5 sekund" },
      { label: "Wszystkie linie", value: "Tramwaje & Autobusy" },
      { label: "Dokładność", value: "Realtime Telemetry" },
    ],
    keyFeatures: [
      "Interaktywna mapa z markerami poruszających się tramwajów",
      "Wyszukiwarka przystanków z tablicami odjazdów w czasie rzeczywistym",
      "Lokalizacja GPS użytkownika i wyznaczanie najbliższego przystanku",
    ],
    architecture: [
      "Integracja z otwartymi danymi telemetrycznymi GTFS-Realtime",
      "Wektorowe kafelki mapy zoptymalizowane pod kątem urządzeń mobilnych",
    ],
  },
  {
    id: "systemrezerw",
    title: "System Rezerwacji 24/7",
    category: "saas",
    categoryLabel: "SaaS / Booking Engine",
    description:
      "Wielobranżowy system rezerwacji terminów online z kalendarzem slotów, automatyczną synchronizacją i powiadomieniami.",
    fullDescription:
      "Zaawansowana platforma rezerwacyjna dla małych i średnich przedsiębiorstw (salony kosmetyczne, gabinety, korty sportowe). Automatyzuje proces bookingu, minimalizuje no-show i wysyła przypomnienia.",
    tags: ["React", "TypeScript", "Calendar Engine", "Tailwind", "REST API"],
    accent: "from-indigo-500/20 to-purple-500/10",
    accentBorder: "hover:border-indigo-500/40",
    accentGlow: "0 0 35px -5px rgba(99,102,241,0.25)",
    image: "https://images.unsplash.com/photo-1506784365847-bbad939e9335?w=800&h=500&fit=crop",
    demo: "https://systemrezerw.vercel.app/",
    featured: false,
    stats: { year: "2025", type: "SaaS" },
    metrics: [
      { label: "Automatyzacja", value: "100% Self-Service" },
      { label: "Spadek no-show", value: "-65%" },
      { label: "Dostępność", value: "24/7/365" },
    ],
    keyFeatures: [
      "Wybór pracownika, usługi i dogodnego wolnego slotu godzinowego",
      "Panel administracyjny do zarządzania grafikami zespołu",
      "Integracja z Kalendarzem Google i Apple Calendar",
    ],
    architecture: [
      "Wydajny silnik generowania slotów czasowych w TypeScript",
      "Zabezpieczenia przed podwójną rezerwacją (Race condition protection)",
    ],
  },
  {
    id: "lucznicza",
    title: "Łucznicza Sports Arena",
    category: "web",
    categoryLabel: "Sport & Obiekty",
    description:
      "Portal obiektu widowiskowo-sportowego: harmonogram wydarzeń, rezerwacja torów łuczniczych i drabinki turniejowe.",
    fullDescription:
      "Oficjalny serwis klubu sportowego i hali łuczniczej. Łączy prezentację osiągnięć zawodników, relacje z turniejów oraz zautomatyzowany system wynajmu stanowisk strzeleckich.",
    tags: ["React", "TypeScript", "Tailwind", "Motion", "Figma Design"],
    accent: "from-emerald-500/20 to-teal-500/10",
    accentBorder: "hover:border-emerald-500/40",
    accentGlow: "0 0 35px -5px rgba(5,150,105,0.25)",
    image: "https://images.unsplash.com/photo-1511886929837-354d827aae26?w=800&h=500&fit=crop",
    demo: "https://lucznicza.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Obiekt Sportowy" },
    metrics: [
      { label: "Wzrost rezerwacji", value: "+140%" },
      { label: "Czas ładowania", value: "0.41s" },
      { label: "Zadowolenie klubu", value: "5.0 ★" },
    ],
    keyFeatures: [
      "Wizualny wybór toru łuczniczego i dystansu (18m, 30m, 50m)",
      "Drabinki pucharowe z wynikami zawodów live",
      "Strefa dla członków klubu z materiałami treningowymi",
    ],
    architecture: [
      "Responsywny design zaprojektowany w Figma z naciskiem na A11y",
      "Płynne animacje sekcji z motion/react",
    ],
  },
  {
    id: "fisz-handel",
    title: "uFISZA Longboard Commerce",
    category: "ecommerce",
    categoryLabel: "E-commerce & Sport",
    description:
      "Sklep internetowy z deskami fiszka i akcesoriami sportowymi. System rekomendacji produktowych i one-step checkout.",
    fullDescription:
      "Projekt stworzony dla marki streetwear i desek fisz. Czysty, nowoczesny interfejs z intuicyjną nawigacją po kolekcjach, wariantami kolorystycznymi w czasie rzeczywistym i szybkim procesem zakupu one-step checkout.",
    tags: ["React", "TypeScript", "Tailwind CSS", "State Machine"],
    accent: "from-teal-500/20 to-cyan-500/10",
    accentBorder: "hover:border-teal-500/40",
    accentGlow: "0 0 35px -5px rgba(20,184,166,0.25)",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=500&fit=crop",
    demo: "https://fisz-handel-c1bb3a8d-uubz.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "E-commerce" },
    metrics: [
      { label: "Ruch mobilny", value: "78%" },
      { label: "Czas zakupu", value: "< 45s" },
      { label: "Zadowolenie", value: "5.0 ★" },
    ],
    keyFeatures: [
      "Szybki koszyk modalny bez przeładowania strony",
      "Wizualny wybór wariantów kolorystycznych i kół",
      "Optymalizacja dla urządzeń mobilnych",
    ],
    architecture: [
      "Stan aplikacji modelowany za pomocą maszyny stanów",
      "Optymalizacja grafik z preloadingiem wariantów",
    ],
  },
  {
    id: "szczecin-styl",
    title: "Szczecin Styl Fashion Boutique",
    category: "ecommerce",
    categoryLabel: "E-commerce & Moda",
    description:
      "Nowoczesna platforma e-commerce dla butiku modowego z dynamicznym filtrowaniem, koszykiem live i płatnościami online.",
    fullDescription:
      "Kompleksowe wdrożenie butiku internetowego Szczecin Styl łączące estetykę high-fashion z ultraszybkim czasem ładowania. Platforma obsługuje automatyczne zarządzanie stanem magazynowym, integrację bramki płatności Stripe/BLIK oraz optymalizację SEO z renderowaniem hybrydowym.",
    tags: ["React 18", "TypeScript", "Tailwind CSS", "Stripe API", "Zustand"],
    accent: "from-purple-500/20 to-pink-500/10",
    accentBorder: "hover:border-purple-500/40",
    accentGlow: "0 0 35px -5px rgba(168,85,247,0.25)",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=500&fit=crop",
    demo: "https://szczecin-styl-main.vercel.app/",
    featured: true,
    stats: { year: "2024", type: "E-commerce" },
    metrics: [
      { label: "Google PageSpeed", value: "98/100" },
      { label: "Wzrost konwersji", value: "+145%" },
      { label: "Czas ładowania", value: "0.45s" },
    ],
    keyFeatures: [
      "Wielopoziomowe filtrowanie kolekcji po rozmiarach, kolorach i cenie",
      "Koszyk z natychmiastową synchronizacją stanu i weryfikacją stanów",
      "Bezpieczne płatności kartą i BLIK z webhookami Stripe",
      "Responsywny panel zarządzania zamówieniami",
    ],
    architecture: [
      "Architektura komponentowa React z TypeScript dla pełnego type-safety",
      "Zustand do ultra-wydajnego zarządzania stanem koszyka",
      "Tailwind CSS ze strategią Zero-Runtime overhead",
    ],
  },
  {
    id: "lysy-smoky",
    title: "Łysy Barber & Smokehouse",
    category: "web",
    categoryLabel: "Portfolio & Rezerwacje",
    description:
      "Ekskluzywne portfolio z systemem rezerwacji wizyt online, interaktywną galerią metamorfoz i opiniami klientów.",
    fullDescription:
      "Dedykowana platforma internetowa dla renomowanego salonu fryzjerskiego. Projekt skupiony na kreowaniu wizerunku premium, responsywnej prezentacji prac oraz płynnym procesie rezerwacji terminów online.",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Motion", "CMS"],
    accent: "from-amber-500/20 to-orange-500/10",
    accentBorder: "hover:border-amber-500/40",
    accentGlow: "0 0 35px -5px rgba(245,158,11,0.25)",
    image: "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800&h=500&fit=crop",
    demo: "https://lysy-smoky.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Portfolio" },
    metrics: [
      { label: "Nowe rezerwacje", value: "+220%" },
      { label: "WCAG Dostępność", value: "100% AA" },
      { label: "Zmniejszony bounce-rate", value: "-40%" },
    ],
    keyFeatures: [
      "Dynamiczny kalendarz rezerwacji terminów",
      "Galeria 'Przed i Po' z suwakiem porównawczym",
      "System opinii z moderacją i integracją Google Reviews",
    ],
    architecture: [
      "Server-Side Rendering (SSR) w Next.js dla maksymalnego SEO",
      "Animacje oparte na GPU z motion/react",
    ],
  },
  {
    id: "notatnik-seven",
    title: "Notatnik Cloud Second-Brain",
    category: "saas",
    categoryLabel: "SaaS / Notatki",
    description:
      "Aplikacja do zarządzania notatkami i wiedzą z synchronizacją w chmurze w czasie rzeczywistym, edytorem Markdown i tagowaniem.",
    fullDescription:
      "Zaawansowana aplikacja typu second-brain ułatwiająca organizację notatek, fragmentów kodu i zadań. Zapewnia natychmiastową synchronizację danych pomiędzy urządzeniami w czasie rzeczywistym oraz pracę w trybie offline-first.",
    tags: ["React", "Firebase Realtime", "TypeScript", "Tailwind", "Markdown"],
    accent: "from-blue-500/20 to-cyan-500/10",
    accentBorder: "hover:border-blue-500/40",
    accentGlow: "0 0 35px -5px rgba(59,130,246,0.25)",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=500&fit=crop",
    demo: "https://notatnik-seven.vercel.app/",
    featured: true,
    stats: { year: "2024", type: "SaaS" },
    metrics: [
      { label: "Latencja synchronizacji", value: "< 25ms" },
      { label: "Tryb Offline", value: "100% PWA" },
      { label: "Uptime", value: "99.99%" },
    ],
    keyFeatures: [
      "Edytor Rich-Text z podświetlaniem składni kodu i Markdown",
      "Synchronizacja w chmurze w czasie rzeczywistym (Realtime Database)",
      "Globalne wyszukiwanie pełnotekstowe z indeksem tagów",
      "Pełne szyfrowanie danych użytkownika",
    ],
    architecture: [
      "Architektura Offline-First z IndexedDB i Firebase Cloud Sync",
      "Optimistic UI updates dla zerowego poczucia opóźnienia",
      "Custom hooki do zarządzania subskrypcjami strumieni danych",
    ],
  },
  {
    id: "ghydra-main",
    title: "Ghydra Agile Workflow SaaS",
    category: "saas",
    categoryLabel: "Fullstack SaaS",
    description:
      "Platforma do zarządzania projektami dla zespołów inżynierskich z interaktywną tablicą Kanban, śledzeniem czasu i kolaboracją live.",
    fullDescription:
      "Kompleksowy system zarządzania workflowem dla zespołów programistycznych. Łączy zarządzanie zadaniami, metryki wydajności sprintów, zintegrowany czat oraz automatyzację powiadomień przez WebSockets.",
    tags: ["React", "Node.js", "MongoDB", "Socket.io", "Express"],
    accent: "from-emerald-500/20 to-green-500/10",
    accentBorder: "hover:border-emerald-500/40",
    accentGlow: "0 0 35px -5px rgba(16,185,129,0.25)",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=500&fit=crop",
    demo: "https://ghydra-main.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Zarządzanie" },
    metrics: [
      { label: "Aktywne zespoły", value: "50+" },
      { label: "Czas reakcji API", value: "32ms" },
      { label: "WebSockets", value: "Live Sync" },
    ],
    keyFeatures: [
      "Interaktywna tablica Kanban typu drag & drop",
      "Śledzenie czasu pracy z eksportem raportów",
      "Wielodostępna edycja w czasie rzeczywistym przez Socket.io",
      "Role i uprawnienia dla członków organizacji",
    ],
    architecture: [
      "Mikroserwisy backendowe w Node.js & Express",
      "Baza danych MongoDB z optymalizowanymi indeksami",
      "Dwukierunkowa komunikacja WebSocket dla powiadomień live",
    ],
  },
  {
    id: "jednoreki",
    title: "Jednoręki Bandit Casino Game",
    category: "web",
    categoryLabel: "Gra Arcade & Canvas",
    description:
      "Klasyczny symulator automatu arcade z fizyką obrotu bębnów, generatorem losowości i efektami dźwiękowymi Web Audio.",
    fullDescription:
      "Wciągająca gra przeglądarkowa symulująca automat z bębnami (Slot Machine). Wykorzystuje renderowanie Canvas 2D, syntezę dźwięku Web Audio API oraz system mnożników wygranych i tabelę rekordów.",
    tags: ["React", "Canvas 2D", "Web Audio API", "TypeScript", "Motion"],
    accent: "from-rose-500/20 to-red-500/10",
    accentBorder: "hover:border-rose-500/40",
    accentGlow: "0 0 35px -5px rgba(225,29,72,0.25)",
    image: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&h=500&fit=crop",
    demo: "https://jednoreki.vercel.app/",
    featured: false,
    stats: { year: "2024", type: "Arcade Game" },
    metrics: [
      { label: "Płynność klatek", value: "60 FPS Canvas" },
      { label: "Dźwięk", value: "Web Audio Synthesizer" },
      { label: "Czas rundy", value: "1.2s" },
    ],
    keyFeatures: [
      "Fizyka obrotu i wyhamowywania bębnów z krzywą easeOutBack",
      "Synteza efektów dźwiękowych wygranej i obrotu w czasie rzeczywistym",
      "Tabela najwyższych wygranych zapisywana lokalnie",
    ],
    architecture: [
      "Wydajny silnik renderowania Canvas 2D z requestAnimationFrame",
      "Dźwięki generowane proceduralnie bez zewnętrznych plików audio",
    ],
  },
  {
    id: "lucasz-elektro-glow",
    title: "Łukasz Elektro Glow Smart",
    category: "ecommerce",
    categoryLabel: "E-commerce & Oświetlenie",
    description:
      "Sklep i serwis profesjonalnych instalacji elektrycznych, systemów Smart Home oraz nowoczesnego oświetlenia LED.",
    fullDescription:
      "Platforma e-commerce dedykowana branży oświetleniowej i instalacji smart home. Wyposażona w inteligentny konfigurator zestawów LED, porównywarkę specyfikacji technicznych oraz bezpieczny moduł płatności.",
    tags: ["React", "TypeScript", "Stripe Checkout", "Tailwind", "Lucide"],
    accent: "from-yellow-500/20 to-amber-500/10",
    accentBorder: "hover:border-yellow-500/40",
    accentGlow: "0 0 35px -5px rgba(234,179,8,0.25)",
    image: "https://images.unsplash.com/photo-1565636192335-14c46fa1120d?w=800&h=500&fit=crop",
    demo: "https://lucasz-elektro-glow.lovable.app/",
    featured: false,
    stats: { year: "2024", type: "E-commerce" },
    metrics: [
      { label: "Katalog produktów", value: "500+ SKU" },
      { label: "Średni koszyk", value: "+35%" },
      { label: "Stripe", value: "Automatyzacja" },
    ],
    keyFeatures: [
      "Zaawansowana wyszukiwarka z filtrami parametrów elektrycznych",
      "Kalkulator poboru mocy i doboru zasilaczy",
      "Generowanie faktur PDF i tracking przesyłek",
    ],
    architecture: [
      "React z architekturą modułową",
      "Integracja Stripe API z obsługą płatności wielowalutowych",
    ],
  },
];
